# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [2]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [ ]:
# Import torch
import torch 



# Create random tensor

rand_tensor= torch.rand(size=(7,7))
rand_tensor

tensor([[0.0223, 0.7869, 0.2057, 0.5216, 0.7456, 0.8032, 0.1104],
        [0.0366, 0.0775, 0.5959, 0.9613, 0.9909, 0.8600, 0.7092],
        [0.1564, 0.6022, 0.0775, 0.4560, 0.2732, 0.7777, 0.9119],
        [0.2898, 0.8270, 0.0631, 0.8074, 0.4405, 0.7032, 0.1900],
        [0.3189, 0.2766, 0.3802, 0.1982, 0.2072, 0.4796, 0.2213],
        [0.7921, 0.3220, 0.7485, 0.3257, 0.2908, 0.8252, 0.0624],
        [0.0423, 0.0023, 0.6582, 0.3807, 0.8340, 0.3896, 0.1034]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [3]:
# Create another random tensor

rand_tensor2 = toe=torch.rand(size=(1,7))

# Perform matrix multiplication 
mult_result = torch.matmul(rand_tensor,rand_tensor2.T)
print (mult_result)

tensor([[1.7630],
        [2.2229],
        [1.7843],
        [2.0578],
        [1.2366],
        [2.1335],
        [1.1916]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [7]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
rand_tensor= torch.rand(size=(7,7))
rand_tensor2= torch.rand(size=(1,7))

# Matrix multiply tensors
mult_result = torch.matmul(rand_tensor,rand_tensor2.T)
mult_result , mult_result.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [9]:
# Set random seed on the GPU

torch.manual_seed(1234)


if torch.cuda.is_available():
    torch.cuda.manual_seed(1234)
    



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [12]:
# Set random seed
torch.manual_seed(1234)


# Check for access to GPU

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
# Create two random tensors on GPU
x = torch.rand(2, 3)
y = torch.rand(2, 3)

x = x.to(device)
y = y.to(device)

print("Device:", device)
print(x)
print(y)

Device: cpu
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]])
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]])



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [13]:
# Perform matmul on tensor_A and tensor_B
result = torch.matmul(x, y.T)

print(result)
print(result.shape)

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]])
torch.Size([2, 2])


### 8. Find the maximum and minimum values of the output of 7.

In [15]:
# Find max
# Find min
max_value = result.max()
min_value = result.min()

print("result:\n", result)
print("max value:", max_value.item())
print("min value:", min_value.item())

result:
 tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]])
max value: 0.5617256760597229
min value: 0.3647301495075226


### 9. Find the maximum and minimum index values of the output of 7.

In [16]:
# Find arg max
# Find arg min
max_index = result.argmax()
min_index = result.argmin()

print("result:\n", result)
print("max index:", max_index.item())
print("min index:", min_index.item())

result:
 tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]])
max index: 3
min index: 0



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [18]:
# Set seed
torch.manual_seed(7)

# Create random tensor

x = torch.rand(1, 1, 1, 10)
# Remove single dimensions
y = x.squeeze()

# Print out tensors and their shapes
print(x, x.shape)
print('#'*60)
print(y, y.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
############################################################
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
